[tool.poetry]
name = "pysdfscad"
version = "0.1.0"
description = ""
authors = ["Alex Davies <traverse.da@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
sdf = {git = "https://github.com/fogleman/sdf.git"}
lark = "^1.1.5"
loguru = "^0.6.0"
click = "^8.1.3"

[tool.poetry.extras]
qtgui = ["PyQt5","QScintilla"]

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
