name: Python package

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    defaults:
      run:
        shell: bash
      
    runs-on: ${{ matrix.os }}
#    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python poetry
        uses: abatilo/actions-poetry@v2

      - name: install project
        run: poetry install --all-extras --no-interaction --no-cache -vvv
        continue-on-error: true

      - run: ./compile.sh
      # Optionally verify that it works (provided that it does not need user interaction)
      #- run: ./dist/your-code/your-code
      - uses: actions/upload-artifact@v3
        with:
          name: build-${{matrix.os}}
          path: dist/*

