name: Python package

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    defaults:
      run:
        shell: bash
      
    runs-on: ${{ matrix.os }}
    timeout-minutes: 100

    steps:
      - name: Add extra packages for local compile
        if: ${{ env.ACT }}
        run: apt update && apt install patchelf
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: install project
        run: poetry install --all-extras

      - name: run compile
        run: ./compile.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
